theme: jekyll-theme-minimal
title: ONG GUO XIANG
description:  >
  Research Assistant at National University of Singapore
  <br><br>
  <a href="/cv.md">CV</a> 
  <br><br>
  <a href="/portfolio.md">Portfolio</a> 
  <br><br>
  <a href="/portfolio.md">Linkedin Profile</a>
