theme: jekyll-theme-minimal
title: ONG GUO XIANG
description:  >
  Research Assistant at National University of Singapore
  <br><br>
  <a href="_site/cv.html">CV</a> 
  <br><br>
  <a href="_site/portfolio.html">Portfolio</a> 
  <br><br>
  <a href="https://www.linkedin.com/">Linkedin Profile</a>
