theme: jekyll-theme-minimal
title: ONG GUO XIANG
logo: /images/profile_gxite.png
description:  >
  Research Assistant at National University of Singapore
  <br><br>
  <a href="cv.html">CV</a> 
  <br><br>
  <a href="portfolio.html">Portfolio</a> 
  <br><br>
  <a href="https://www.linkedin.com/">Linkedin Profile</a>
