theme: jekyll-theme-minimal
title: ONG GUO XIANG
logo: /images/profile_gx_c.jpg
description:  >
  Research Assistant at National University of Singapore
  <br><br>
  <a href="https://www.linkedin.com/in/ongguoxiang/">Linkedin</a>
  <br><br> 
  <a href="https://github.com/gxite">Github</a>
  <br><br> 
  <a href="https://gxite.github.io/portfolio.html">Portfolio</a>
  <br><br> 
  <a href="https://gxite.github.io/portfolio/cv_2020_11.pdf">CV</a>

