theme: jekyll-theme-minimal
title: ONG GUO XIANG
logo: /images/profile_gx_c.jpg
description:  >
  Research Assistant at National University of Singapore
  <br><br>
  <a href="/portfolio/pdf/CV_ong_guo_xiang.pdf">CV</a> 
  <br><br>
  <a href="portfolio.html">Portfolio</a> 
  <br><br>
  <a href="https://www.linkedin.com/">Linkedin</a>
