theme: jekyll-theme-minimal
title: ONG GUO XIANG
logo: /images/profile_gx_c.jpg
description:  >
  Research Assistant at National University of Singapore
  <br><br>
  <a href="/portfolio/cv_2019_11.pdf">CV</a> 
  <br><br>
  <a href="portfolio.html">Portfolio</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/ongguoxiang/">Linkedin</a>
  <br><br> 
  <a href="https://github.com/gxite">Github</a>

